apiVersion: v1
kind: Pod
metadata:
  name: csvserver-pod
  labels: 
    name: csvserver-pod
    app: csvserver-app
spec:
  containers:
    - name: csvserver-app
      image: infracloudio/csvserver
      ports:
        - containerPort: 9300
      volumeMounts:
      - name: data-volume
        mountPath: /csvserver/inputdata
        subPath: inputdata
      envFrom:
        - configMapRef:
            name: app-config
  volumes:
  - name: data-volume
    configMap:
      name: csv-inputdata

