apiVersion: v1
kind: Service
metadata:
  name: csvserver-external-service
  labels:
    name: csvserver-external-service
    app: csvserver-app
spec:
  type: NodePort
  ports:
    - port: 9393
      targetPort: 9300
      nodePort: 30001
  selector:
    name: csvserver-app-pod
    app: csvserver-app
